# Generated by Django on 2026-05-26
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Tenant",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=200)),
                ("slug", models.SlugField(max_length=200, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Tenant",
                "verbose_name_plural": "Tenants",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="DataSource",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "source_type",
                    models.CharField(
                        choices=[("SAP", "SAP"), ("UTILITY", "Utility"), ("TRAVEL", "Travel")],
                        max_length=20,
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("config", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=models.deletion.CASCADE,
                        related_name="data_sources",
                        to="ingestion.tenant",
                    ),
                ),
            ],
            options={
                "verbose_name": "Data Source",
                "verbose_name_plural": "Data Sources",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="EmissionFactor",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "source_type",
                    models.CharField(
                        choices=[("SAP", "SAP"), ("UTILITY", "Utility"), ("TRAVEL", "Travel")],
                        max_length=20,
                    ),
                ),
                ("activity_type", models.CharField(max_length=100)),
                ("region", models.CharField(blank=True, max_length=50)),
                ("factor", models.DecimalField(decimal_places=6, max_digits=20)),
                ("unit", models.CharField(max_length=50)),
                ("valid_from", models.DateField()),
                ("valid_to", models.DateField(blank=True, null=True)),
                ("source_reference", models.CharField(blank=True, max_length=255)),
            ],
            options={
                "verbose_name": "Emission Factor",
                "verbose_name_plural": "Emission Factors",
                "ordering": ["source_type", "activity_type", "-valid_from"],
            },
        ),
        migrations.CreateModel(
            name="IngestionRun",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("PROCESSING", "Processing"),
                            ("DONE", "Done"),
                            ("FAILED", "Failed"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                ("file_name", models.CharField(blank=True, max_length=255)),
                ("raw_file", models.FileField(blank=True, null=True, upload_to="ingestion_raw/")),
                ("row_count", models.PositiveIntegerField(default=0)),
                ("error_count", models.PositiveIntegerField(default=0)),
                (
                    "data_source",
                    models.ForeignKey(
                        on_delete=models.deletion.CASCADE,
                        related_name="ingestion_runs",
                        to="ingestion.datasource",
                    ),
                ),
                (
                    "triggered_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=models.deletion.SET_NULL,
                        related_name="ingestion_runs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Ingestion Run",
                "verbose_name_plural": "Ingestion Runs",
                "ordering": ["-started_at"],
            },
        ),
        migrations.CreateModel(
            name="NormalizedRecord",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "source_type",
                    models.CharField(
                        choices=[("SAP", "SAP"), ("UTILITY", "Utility"), ("TRAVEL", "Travel")],
                        max_length=20,
                    ),
                ),
                (
                    "scope",
                    models.CharField(
                        choices=[
                            ("SCOPE_1", "Scope 1"),
                            ("SCOPE_2", "Scope 2"),
                            ("SCOPE_3", "Scope 3"),
                        ],
                        max_length=20,
                    ),
                ),
                ("activity_date", models.DateField()),
                ("quantity", models.DecimalField(decimal_places=6, max_digits=20)),
                ("unit", models.CharField(max_length=50)),
                ("quantity_co2e", models.DecimalField(blank=True, decimal_places=6, max_digits=20, null=True)),
                (
                    "emission_factor_used",
                    models.DecimalField(blank=True, decimal_places=6, max_digits=20, null=True),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("APPROVED", "Approved"),
                            ("REJECTED", "Rejected"),
                            ("FLAGGED", "Flagged"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                ("is_locked", models.BooleanField(default=False)),
                ("extra", models.JSONField(blank=True, default=dict)),
                ("raw_record", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "ingestion_run",
                    models.ForeignKey(
                        on_delete=models.deletion.CASCADE,
                        related_name="normalized_records",
                        to="ingestion.ingestionrun",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=models.deletion.CASCADE,
                        related_name="normalized_records",
                        to="ingestion.tenant",
                    ),
                ),
            ],
            options={
                "verbose_name": "Normalized Record",
                "verbose_name_plural": "Normalized Records",
                "ordering": ["-activity_date", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="AuditEntry",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("CREATED", "Created"),
                            ("EDITED", "Edited"),
                            ("APPROVED", "Approved"),
                            ("REJECTED", "Rejected"),
                            ("FLAGGED", "Flagged"),
                        ],
                        max_length=20,
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("note", models.TextField(blank=True)),
                ("diff", models.JSONField(blank=True, default=dict)),
                (
                    "normalized_record",
                    models.ForeignKey(
                        on_delete=models.deletion.CASCADE,
                        related_name="audit_entries",
                        to="ingestion.normalizedrecord",
                    ),
                ),
                (
                    "performed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=models.deletion.SET_NULL,
                        related_name="audit_entries",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Audit Entry",
                "verbose_name_plural": "Audit Entries",
                "ordering": ["-timestamp"],
            },
        ),
        migrations.AddIndex(
            model_name="datasource",
            index=models.Index(fields=["tenant"], name="ingestion_d_tenant_1b75c1_idx"),
        ),
        migrations.AddIndex(
            model_name="datasource",
            index=models.Index(fields=["source_type"], name="ingestion_d_source__8fd2ed_idx"),
        ),
        migrations.AddIndex(
            model_name="emissionfactor",
            index=models.Index(fields=["source_type"], name="ingestion_e_source__2b9105_idx"),
        ),
        migrations.AddIndex(
            model_name="ingestionrun",
            index=models.Index(fields=["status"], name="ingestion_i_status_68b0f3_idx"),
        ),
        migrations.AddIndex(
            model_name="normalizedrecord",
            index=models.Index(fields=["tenant"], name="ingestion_n_tenant_ef349c_idx"),
        ),
        migrations.AddIndex(
            model_name="normalizedrecord",
            index=models.Index(fields=["status"], name="ingestion_n_status_04cf36_idx"),
        ),
        migrations.AddIndex(
            model_name="normalizedrecord",
            index=models.Index(fields=["activity_date"], name="ingestion_n_activit_5a1df2_idx"),
        ),
        migrations.AddIndex(
            model_name="normalizedrecord",
            index=models.Index(fields=["source_type"], name="ingestion_n_source__5905f3_idx"),
        ),
    ]
